#import <Foundation/Foundation.h>
#import "OAIAPIResponse.h"
#import "OAIButtonMessagePayload.h"
#import "OAIButtonMessageWithMediaPayload.h"
#import "OAIContactMessagePayload.h"
#import "OAIInstancesInstanceKeySendAudioPostRequest.h"
#import "OAIInstancesInstanceKeySendDocumentPostRequest.h"
#import "OAIInstancesInstanceKeySendImagePostRequest.h"
#import "OAIInstancesInstanceKeySendUploadPostRequest.h"
#import "OAIInstancesInstanceKeySendVideoPostRequest.h"
#import "OAIListMessagePayload.h"
#import "OAILocationMessagePayload.h"
#import "OAIPollMessagePayload.h"
#import "OAISendMediaPayload.h"
#import "OAITemplateButtonPayload.h"
#import "OAITemplateButtonWithMediaPayload.h"
#import "OAITextMessage.h"
#import "OAIApi.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAIMessageSendingApi: NSObject <OAIApi>

extern NSString* kOAIMessageSendingApiErrorDomain;
extern NSInteger kOAIMessageSendingApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Send raw audio.
/// Sends a audio message by uploading to the WhatsApp servers every time. This is not recommended for bulk sending.
///
/// @param instanceKey Instance key
/// @param to The recipient&#39;s number
/// @param instancesInstanceKeySendAudioPostRequest 
/// @param caption Attached caption (optional)
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendAudioPostWithInstanceKey: (NSString*) instanceKey
    to: (NSString*) to
    instancesInstanceKeySendAudioPostRequest: (OAIInstancesInstanceKeySendAudioPostRequest*) instancesInstanceKeySendAudioPostRequest
    caption: (NSString*) caption
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a button message with a media header.
/// Sends an interactive button message to the given user. This message also has media header with it. Make sure that all the button ids are unique
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendButtonMediaPostWithInstanceKey: (NSString*) instanceKey
    data: (OAIButtonMessageWithMediaPayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a button message.
/// Sends an interactive button message to the given user. Make sure that all the button ids are unique
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendButtonsPostWithInstanceKey: (NSString*) instanceKey
    data: (OAIButtonMessagePayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a contact message.
/// Sends a contact (vcard) message to the given user.
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendContactPostWithInstanceKey: (NSString*) instanceKey
    data: (OAIContactMessagePayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send raw document.
/// Sends a document message by uploading to the WhatsApp servers every time. This is not recommended for bulk sending.
///
/// @param instanceKey Instance key
/// @param to The recipient&#39;s number
/// @param instancesInstanceKeySendDocumentPostRequest 
/// @param caption Attached caption (optional)
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendDocumentPostWithInstanceKey: (NSString*) instanceKey
    to: (NSString*) to
    instancesInstanceKeySendDocumentPostRequest: (OAIInstancesInstanceKeySendDocumentPostRequest*) instancesInstanceKeySendDocumentPostRequest
    caption: (NSString*) caption
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send raw image.
/// Sends a image message by uploading to the WhatsApp servers every time. This is not recommended for bulk sending.
///
/// @param instanceKey Instance key
/// @param to The recipient&#39;s number
/// @param instancesInstanceKeySendImagePostRequest 
/// @param caption Attached caption (optional)
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendImagePostWithInstanceKey: (NSString*) instanceKey
    to: (NSString*) to
    instancesInstanceKeySendImagePostRequest: (OAIInstancesInstanceKeySendImagePostRequest*) instancesInstanceKeySendImagePostRequest
    caption: (NSString*) caption
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a List message.
/// Sends an interactive List message to the given user.
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendListPostWithInstanceKey: (NSString*) instanceKey
    data: (OAIListMessagePayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a location message.
/// Sends a location message to the given user. This is static location and does not update Note: The Address and Url fields are optional
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendLocationPostWithInstanceKey: (NSString*) instanceKey
    data: (OAILocationMessagePayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a media message.
/// Sends a media message to the given user.
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendMediaPostWithInstanceKey: (NSString*) instanceKey
    data: (OAISendMediaPayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a Poll message.
/// Sends an interactive poll message to the given user. The poll message is a new feature that is currently in beta.
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendPollPostWithInstanceKey: (NSString*) instanceKey
    data: (OAIPollMessagePayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a template message with media.
/// Sends an interactive template message with a media header to the given user. Note: The valid button types are \"replyButton\", \"urlButton\", \"callButton\"
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendTemplateMediaPostWithInstanceKey: (NSString*) instanceKey
    data: (OAITemplateButtonWithMediaPayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a template message.
/// Sends an interactive template message to the given user. Note: The valid button types are \"replyButton\", \"urlButton\", \"callButton\"
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendTemplatePostWithInstanceKey: (NSString*) instanceKey
    data: (OAITemplateButtonPayload*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send a text message.
/// Sends a text message to the given user.
///
/// @param instanceKey Instance key
/// @param data Message data
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendTextPostWithInstanceKey: (NSString*) instanceKey
    data: (OAITextMessage*) data
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Upload media.
/// Uploads media to WhatsApp servers and returns the media keys. Store the returned media keys, as you will need them to send media messages
///
/// @param instanceKey Instance key
/// @param type Media type
/// @param instancesInstanceKeySendUploadPostRequest 
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendUploadPostWithInstanceKey: (NSString*) instanceKey
    type: (NSString*) type
    instancesInstanceKeySendUploadPostRequest: (OAIInstancesInstanceKeySendUploadPostRequest*) instancesInstanceKeySendUploadPostRequest
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;


/// Send raw video.
/// Sends a video message by uploading to the WhatsApp servers every time. This is not recommended for bulk sending.
///
/// @param instanceKey Instance key
/// @param to The recipient&#39;s number
/// @param instancesInstanceKeySendVideoPostRequest 
/// @param caption Attached caption (optional)
/// 
///  code:200 message:"Success",
///  code:400 message:"Bad Request",
///  code:401 message:"Unauthorized",
///  code:404 message:"Instance not found",
///  code:500 message:"Internal Server Error"
///
/// @return OAIAPIResponse*
-(NSURLSessionTask*) instancesInstanceKeySendVideoPostWithInstanceKey: (NSString*) instanceKey
    to: (NSString*) to
    instancesInstanceKeySendVideoPostRequest: (OAIInstancesInstanceKeySendVideoPostRequest*) instancesInstanceKeySendVideoPostRequest
    caption: (NSString*) caption
    completionHandler: (void (^)(OAIAPIResponse* output, NSError* error)) handler;



@end
