#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIFileUpload
@end

@interface OAIFileUpload : OAIObject


@property(nonatomic) NSString* directPath;

@property(nonatomic) NSArray<NSNumber*>* fileEncSha256;

@property(nonatomic) NSNumber* fileLength;

@property(nonatomic) NSArray<NSNumber*>* fileSha256;

@property(nonatomic) NSArray<NSNumber*>* mediaKey;

@property(nonatomic) NSString* mimeType;

@property(nonatomic) NSString* url;

@end
