#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIListItem.h"
@protocol OAIListItem;
@class OAIListItem;



@protocol OAIListSection
@end

@interface OAIListSection : OAIObject


@property(nonatomic) NSArray<OAIListItem>* rows;

@property(nonatomic) NSString* title;

@end
