#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIStructsTemplateButton
@end

@interface OAIStructsTemplateButton : OAIObject

/* Make sure this is unique [optional]
 */
@property(nonatomic) NSString* buttonId;

@property(nonatomic) NSString* payload;

@property(nonatomic) NSString* title;
/* Valid types are replyButton, urlButton & callButton 
 */
@property(nonatomic) NSString* type;

@end
