#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIStructsLocationMessagePayloadLocation.h"
@protocol OAIStructsLocationMessagePayloadLocation;
@class OAIStructsLocationMessagePayloadLocation;



@protocol OAIStructsLocationMessagePayload
@end

@interface OAIStructsLocationMessagePayload : OAIObject


@property(nonatomic) OAIStructsLocationMessagePayloadLocation* location;

@property(nonatomic) NSString* to;

@property(nonatomic) NSString* url;

@end
