#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIStructsListItem.h"
@protocol OAIStructsListItem;
@class OAIStructsListItem;



@protocol OAIStructsListSection
@end

@interface OAIStructsListSection : OAIObject


@property(nonatomic) NSArray<OAIStructsListItem>* rows;

@property(nonatomic) NSString* title;

@end
