#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIStructsFileUpload.h"
#import "OAIStructsTemplateButton.h"
@protocol OAIStructsFileUpload;
@class OAIStructsFileUpload;
@protocol OAIStructsTemplateButton;
@class OAIStructsTemplateButton;



@protocol OAIStructsTemplateButtonWithMediaPayload
@end

@interface OAIStructsTemplateButtonWithMediaPayload : OAIObject


@property(nonatomic) NSArray<OAIStructsTemplateButton>* buttons;

@property(nonatomic) NSString* contentText;

@property(nonatomic) NSString* footer;

@property(nonatomic) OAIStructsFileUpload* media;

@property(nonatomic) NSString* to;

@end
