#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIStructsGroupUpdateDescriptionPayload
@end

@interface OAIStructsGroupUpdateDescriptionPayload : OAIObject


@property(nonatomic) NSString* _description;

@end
