#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* WhatsAPI Go
* The V2 of WhatsAPI Go
*
* The version of the OpenAPI document: 2.0
* Contact: manjit@sponsorbook.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIStructsListSection.h"
@protocol OAIStructsListSection;
@class OAIStructsListSection;



@protocol OAIStructsListMessagePayload
@end

@interface OAIStructsListMessagePayload : OAIObject


@property(nonatomic) NSString* buttonText;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* multiSelect;

@property(nonatomic) NSArray<OAIStructsListSection>* sections;

@property(nonatomic) NSString* text;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* to;

@end
